PllDoctor/Controllers/RoleController.cs
using AutoMapper;
using Dll.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PllDoctor.DTO;
using PllDoctor.Models;

namespace PllDoctor.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly IMapper _mapper;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(IMapper mapper, RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _mapper = mapper;
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public RoleManager<IdentityRole> RoleManager { get; }
        public async Task<IActionResult> Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var Role = await _roleManager.Roles.ToListAsync();
                var MappedRole = _mapper.Map<IEnumerable<IdentityRole>, IEnumerable<RoleViewModel>>(Role);
                return View(MappedRole);
            }
            else
            {
                var Role = await _roleManager.FindByNameAsync(SearchValue);
                var mappedRole = _mapper.Map<IdentityRole, RoleViewModel>(Role);
                return View(new List<RoleViewModel>() { mappedRole });//cause the view render above for IEnumrable of object 
            }
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var mappedRole = _mapper.Map<RoleViewModel, IdentityRole>(model);
                await _roleManager.CreateAsync(mappedRole);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var Role = await _roleManager.FindByIdAsync(id);
            if (Role is null)
                return NotFound();

            var MappedRole = _mapper.Map<IdentityRole, RoleViewModel>(Role);
            return View(ViewName, MappedRole);
        }

        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var Role = await _roleManager.FindByIdAsync(model.Id);
                    Role.Name = model.RoleName;
                    await _roleManager.UpdateAsync(Role);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);

                }
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(string Id)
        {
            return await Details(Id, "Delete");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {

                var Role = await _roleManager.FindByIdAsync(model.Id);
                if (Role != null)
                {
                    try
                    {
                        await _roleManager.DeleteAsync(Role);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", ex.Message);
                        return RedirectToAction("Error", "Home");
                    }
                }
                else
                    return BadRequest();

            }
            return View(model);
        }

        public async Task<IActionResult> AddOrRemoveUsers(string roleid)
        {
            var role = await _roleManager.FindByIdAsync(roleid);
            if (role is null)
                return NotFound();
            ViewBag.RoleId = roleid;
            var UsersInRole = new List<UserInRoleViewModel>();
            var Users = await _userManager.Users.ToListAsync();//to get all users
            foreach (var user in Users)
            {
                var UserInRole = new UserInRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                    UserInRole.IsSelected = true;
                else
                    UserInRole.IsSelected = false;
                UsersInRole.Add(UserInRole);

            }
            return View(UsersInRole);

        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleid, List<UserInRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(roleid);
            if (role is null)
                return BadRequest();

            if (ModelState.IsValid)
            {

                foreach (var user in users)
                {
                    var AppUser = await _userManager.FindByIdAsync(user.UserId);
                    if (AppUser != null)
                    {
                        if (user.IsSelected && !await _userManager.IsInRoleAsync(AppUser, role.Name))
                        {//this mean that this user checked and previous he not have this role 
                            await _userManager.AddToRoleAsync(AppUser, role.Name);
                        }
                        else if (!user.IsSelected && await _userManager.IsInRoleAsync(AppUser, role.Name))
                        {//this mean that user not checked and has this role so it must delete from him
                            await _userManager.RemoveFromRoleAsync(AppUser, role.Name);
                        }
                    }

                }
                return RedirectToAction(nameof(Edit), new { id = roleid });


            }
            return View(users);
        }
    }
}

PllDoctor/Controllers/SubjectController.cs
using AutoMapper;
using Bll.Interfaces_Repository;
using Dll.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PllDoctor.DTO;
using PllDoctor.Models;

namespace PllDoctor.Controllers
{
    [Authorize(Roles = "Doctor,Admin")]

    public class SubjectController : Controller
    {

        private readonly IUniteOfWork _uniteOfWork;
        private readonly IMapper _mapper;
        private readonly ILogger<SubjectController> _logger;



        public SubjectController(IUniteOfWork uniteOfWork, IMapper mapper, ILogger<SubjectController> logger)
        {

            _uniteOfWork = uniteOfWork;
            _mapper = mapper;
            _logger = logger;

        }

        public IActionResult GetAllSubjects(string? SubjectName)
        {
            if (User.IsInRole("Doctor") || User.IsInRole("Admin"))
            {
                // IEnumerable<SubjectViewModel> subject;
                if (string.IsNullOrEmpty(SubjectName))
                {
                    var subjects = _uniteOfWork.SubjectRepository.GetAll();
                    var mapped = _mapper.Map<IEnumerable<Subject>, IEnumerable<SubjectViewModel>>(subjects);
                    return View(mapped);
                }
                else

                {
                    var subjects = _uniteOfWork.SubjectRepository.SearchByName(SubjectName);
                    var mapped = _mapper.Map<IEnumerable<Subject>, IEnumerable<SubjectViewModel>>(subjects);
                    return View(mapped);
                }
            }

            return RedirectToAction(nameof(AccessDenied));
        }
        [HttpGet]
        public IActionResult AddSubjects()
        {

            return View();
        }
        [HttpPost]
        public IActionResult AddSubjects(SubjectViewModel subject)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var MappedSubject = _mapper.Map<SubjectViewModel, Subject>(subject);
                    _uniteOfWork.SubjectRepository.Add(MappedSubject);
                    int result = _uniteOfWork.Complete();
                    if (result > 0)
                        return RedirectToAction("GetAllSubjects");
                    else
                        return BadRequest();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(subject);
        }
        public IActionResult DeleteSubjects(int? id)
        {
            if (User.IsInRole("Admin"))
            {
                if (id is null)
                    return View("Error");

                var sub = _uniteOfWork.SubjectRepository.GetbyId(id.Value);
                _uniteOfWork.SubjectRepository.Delete(sub);
                int result = _uniteOfWork.Complete();
                if (result > 0)
                {
                    TempData["Removed"] = "Subject deleted Successfully ..!";
                }
                else
                    return BadRequest();
                return RedirectToAction("GetAllSubjects");
            }
            return RedirectToAction(nameof(AccessDenied));
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (User.IsInRole("Admin"))
            {
                if (id is null)
                    return BadRequest();

                var subject = _uniteOfWork.SubjectRepository.GetbyId(id.Value);
                if (subject is null)
                    return NotFound();

                return View(subject);
            }
            else
                return RedirectToAction(nameof(AccessDenied));
        }
        [HttpPost]

        public IActionResult Update(Subject subject, [FromRoute] int id)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    _uniteOfWork.SubjectRepository.Update(subject);
                    int result = _uniteOfWork.Complete();
                    if (result > 0)
                    {
                        TempData["Updated"] = $"{subject.Name} Updated Successfully ..!";
                        return RedirectToAction("GetAllSubjects");
                    }
                    else
                        return BadRequest();

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(subject);
        }
        public IActionResult AccessDenied()
        {
            return View();
        }

    }

}

PllDoctor/Controllers/UserController.cs
using AutoMapper;
using Dll.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PllDoctor.Views.Account;

namespace PllDoctor.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _user;
        private readonly IMapper _mapper;

        public UserController(UserManager<ApplicationUser> user, IMapper mapper)
        {
            _user = user;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var User = _user.Users.Select(
                    U => new UserViewModel()
                    {
                        Name = U.Name,
                        Email = U.Email,
                        Id = U.Id,
                        Roles = _user.GetRolesAsync(U).Result//used Result to aVoid async 
                    });
                return View(User);
            }
            else
            {
                var User = await _user.FindByEmailAsync(SearchValue);
                if (User is not null)
                {
                    var MappedUser = new UserViewModel()//Manual mapping
                    {
                        Id = User.Id,
                        Email = User.Email,
                        Name = User.Name,
                        Roles = _user.GetRolesAsync(User).Result//used Result to aVoid async 
                    };
                    return View(new List<UserViewModel> { MappedUser });//To Put mapped output in the List To return as IEnumrable For Result Of if and Result of }Else
                }
                return NotFound();
            }

        }

        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var User = await _user.FindByIdAsync(id);
            if (User is null)
                return NotFound();

            var MappedUser = _mapper.Map<ApplicationUser, UserViewModel>(User);
            return View(ViewName, MappedUser);
        }

        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserViewModel model)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var User = await _user.FindByIdAsync(model.Id);
                    await _user.UpdateAsync(User);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);

                }
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(string Id)
        {
            return await Details(Id, "Delete");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(UserViewModel model)
        {
            if (ModelState.IsValid)
            {

                var user = await _user.FindByIdAsync(model.Id);
                if (user != null)
                {
                    try
                    {
                        await _user.DeleteAsync(user);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", ex.Message);
                        return RedirectToAction("Error", "Home");
                    }
                }
                else
                    return BadRequest();

            }
            return View(model);
        }
    }
}

PllDoctor/Views/Shared/ProjectLayOut.cshtml
<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Responsive Login and Signup Form </title>

        <!-- CSS -->
    <link rel="stylesheet" href="css/Style.css">
    <link rel="stylesheet" href="css/style2.css">
                
        <!-- Boxicons CSS -->
        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    
</head>
    <body>
        <section class="container forms">
            <div class="form login">
                <div class="form-content">
                    <header>Login
                    <div class="container">
                        <main role="main" class="pb-3">
                            @RenderBody()
                        </main>
                    </div>

                    </header>
                    

            <!-- Signup Form -->

       
        </section>

        <!-- JavaScript -->
        <script src="js/script.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

PllDoctor/Views/Shared/_AccessDenied.cshtml
@{
    ViewData["Title"] = "_AccessDenied";
}

<!DOCTYPE html>
<html>
<head>
    <title>Ended Progress</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        body {
            background-color: black;
            color: white;
        }

        h1 {
            color: red;
        }

        h6 {
            color: red;
            text-decoration: underline;
        }</style>


</head>
<body class="body">
    @RenderBody()
</body>
</html>

PllDoctor/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Attendance QR Code System </title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="~/css/st/style.css" rel="stylesheet" />
	@* <link rel="stylesheet" href="~/css/Style.css" asp-append-version="true" /> *@
<!-- //Custom Theme files -->
    <!-- web font -->
    <link href="~/css/site.css" rel="stylesheet" />
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
	
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<div class="container body-content">
			@RenderBody()	
		</div>
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>
				©  Design Under Supervision  Of Prof. Dr. Omina Elbarbary 
			</p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
		<script src="~/lib/jquery/dist/jquery.min.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
		@await RenderSectionAsync("Scripts",required:false)
</body>
</html> 

PllDoctor/Views/Shared/_ButtonsPartialView.cshtml
@model string
<td><a asp-action="Edit" asp-route-id="@Model"><i class="fas fa-edit text-warning"></i></a></td>
<td><a asp-action="Details" asp-route-id="@Model"><i class="fas fa-eye text-info"></i></a></td>
<td><a asp-action="Delete" asp-route-id="@Model"><i class="fas fa-trash text-danger"></i></a></td>

PllDoctor/Views/Shared/_HomeLayOut.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Attendance QR Code System </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<link rel="stylesheet" href="~/css/Style.css" asp-append-version="true" />
	
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">

</head>
<body>
	<header>
	<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
					
			<a class="btn btn-outline-primary bg-dark text-danger" asp-area="" asp-controller="Subject" asp-action="GetAllSubjects">Previous</a>

	</nav>
	</header>

	
	<!-- main -->
	<div class="main-w3layouts wrapper">

		<div class="container body-content">
			@RenderBody()
		</div>
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

PllDoctor/Views/Shared/_Layout.cshtml
@using PllDoctor.Views.Account
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> signinManager
@{
    ApplicationUser user = await UserManager.GetUserAsync(User);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PllDoctor</title>
   
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PllDoctor.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="">Welcome Doctor @user.Name</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <div class="d-flex flex-row">
                        <ul class="navbar-nav navbar-expand-lg">
                         
                            @if (signinManager.IsSignedIn(User) && User.IsInRole("Admin"))
                       {
                            <li><a asp-action="AddSubjects" class=" text-success"><i class="fas fa-plus ">Add Subject</i></a></li>
                            
                            <li><a asp-action="Index" asp-controller="User" class=" text-success m-3 border-2"><i class="fas fa-Search ">Users</i></a></li>
                            <li><a asp-action="Index" asp-controller="Role" class=" text-success m-3 border-2"><i class="fas fa-Search ">Roles</i></a></li>
                       }
                            
                        </ul>
                    </div>
                    <div>
                        <ul class="navbar-nav">
                            @if (signinManager.IsSignedIn(User))
                            {
                                <li class="nav-item ml-auto">
                                <form asp-action="SignOut" asp-controller="Account">
                                        <input type="submit" value="Sign Out" class="nav-link text-light btn-danger" />
                            </form> 
                                </li>
                             } 
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <div class="main-w3layouts wrapper">
            <div class="container body-content">
                @RenderBody()
            </div>
            
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PllDoctor/Views/Shared/_TheEnd.cshtml
@{
    ViewData["Title"] = "_TheEnd";
}

<!DOCTYPE html>
<html >
<head>
    <title>UnAuthorized User</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="_TheEndLayOut" />
   
        <style >
        body {
            background-color: black;
            color: white;
        }

        h1 {
            color: red;
        }

        h6 {
            color: red;
            text-decoration: underline;
        }</style>

</head>
<body class="body">
    @RenderBody()
</body>
</html>