PllDoctor/Controllers/AttendanceController.cs
using AutoMapper;
using Bll.Interfaces_Repository;
using ClosedXML.Excel;
using Dll.DataContext;
using Dll.Entity;
//using DocumentFormat.OpenXml.Drawing.Charts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PllDoctor.DTO;
using PllDoctor.Models;
using System.Data;

namespace PllDoctor.Controllers
{
    [Authorize]
    public class AttendanceController : Controller
    {

        private readonly IUniteOfWork _uniteOfWork;
        private readonly IMapper _mapper;
        private readonly SystemDbContext _dbContext;

        public AttendanceController(IUniteOfWork uniteOfWork, IMapper mapper, SystemDbContext dbContext)
        {

            _uniteOfWork = uniteOfWork;
            _mapper = mapper;
            _dbContext = dbContext;
        }

        [HttpPost]
        public IActionResult CreateQRCode(string Name)
        {
            string name = Name;
            if (name is not null)
            {
                string[] arr = QRCodeGeneratorService.GenerateQRCode(_uniteOfWork, name);
                #region For View
                ViewBag.QrCodeUri0 = arr[0];
                ViewBag.QrCodeUri1 = arr[1];
                ViewBag.QrCodeUri2 = arr[2];
                #endregion 

            }
            return View();
        }
        //Show Attendance
        [HttpPost]
        public IActionResult GetAttendance(string SubjectName, DateTime? dateTime)
        {
            if (!string.IsNullOrEmpty(SubjectName))  //get All Attendance subject
            {
                IQueryable<AttendanceTable> CustomAttendance;
                TempData["subject"] = SubjectName;

                if (dateTime is null)
                {
                    CustomAttendance = _uniteOfWork.AttendanceRepository.GetRequiredAttendance(SubjectName, DateTime.Today);//To get Attendance For This day 
                }
                else { CustomAttendance = _uniteOfWork.AttendanceRepository.GetRequiredAttendance(SubjectName, dateTime); }
                if (CustomAttendance != null)
                {
                    var mappedAttendance = _mapper.Map<IEnumerable<AttendanceTable>, IEnumerable<AttendanceModelDTO>>(CustomAttendance);
                    return View(mappedAttendance);
                }
                else
                    return BadRequest();
            }
            else
            {
                var Attendance = _uniteOfWork.AttendanceRepository.GetAll();
                var mappedAttendance = _mapper.Map<IEnumerable<AttendanceTable>, IEnumerable<AttendanceModelDTO>>(Attendance);
                return View(mappedAttendance);
            }

        }

        [HttpPost]
        public FileResult ExportFile(string SubjectName)
        {
            IQueryable<AttendanceTable> CustomAttendance;
            CustomAttendance = _uniteOfWork.AttendanceRepository.GetRequiredAttendance(SubjectName, DateTime.Today);

            var Attendance = _mapper.Map<IEnumerable<AttendanceTable>, IEnumerable<AttendanceModelDTO>>(CustomAttendance);

            var FileName = "Attendance.xlsx";
            return GenerateExcel(FileName, Attendance);


        }

        private FileResult GenerateExcel(string FileName, IEnumerable<AttendanceModelDTO> attendanceModels)
        {
            DataTable dataTable = new DataTable("attendanceModels");
            dataTable.Columns.AddRange(new DataColumn[]
            {
                new DataColumn("Student Name"),
                new DataColumn("Student ID")
            });
            foreach (var item in attendanceModels)
            {
                dataTable.Rows.Add(item.StudentName, item.STDId);
            }
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dataTable);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", FileName);
                }
            }
        }

        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddStudent(AttendanceModelDTO attendanceModel)
        {
            if (ModelState.IsValid)
            {
                var mapped = _mapper.Map<AttendanceModelDTO, AttendanceTable>(attendanceModel);
                _uniteOfWork.AttendanceRepository.Add(mapped);
                var result = _uniteOfWork.Complete();
                if (result > 0)
                    return RedirectToAction("GetAllSubjects", "Subject");
                return View(mapped);

            }
            return View(attendanceModel);
        }

        [HttpDelete]
        public async Task DeleteQRAsync()
        {
            var lastRow = await _dbContext.QRCodesTable
                                     .OrderByDescending(x => x.Id)
                                     .FirstOrDefaultAsync();
            if (lastRow != null)
            {
                // Remove the last row
                _dbContext.QRCodesTable.Remove(lastRow);
                _uniteOfWork.Complete(); // Commit changes to the database
            }
        }

        public IActionResult TheEnd()
        {
            return View();
        }

    }
}

PllDoctor/Views/Attendance/AddStudent.cshtml
@using PllDoctor.DTO
@model AttendanceModelDTO
@{
    ViewData["Title"] = "AddStudent";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var name = TempData["subject"];
    DateTime date = DateTime.Today;
}
<header>
    <style>
        .custom-label {
            font-size: 18px; /* Adjust the font size as needed */
            font-weight: bold;
        }
        </style>
    <center><h1><strong>Add Student To Attendance</strong></h1></center>
</header>
<body>
<form asp-action="AddStudent" asp-controller="Attendance">
    <div class="mb-3">
        <label asp-for="@Model.StudentName" class="form-label custom-label">Student Name</label>
        <input asp-for="@Model.StudentName" type="text" class="form-control">

    </div>
    <div class="mb-3">
        <label asp-for="STDId" class="form-label custom-label">Student ID</label>
        <input asp-for="STDId" type="text" class="form-control">
   
    </div>
        <div class="mb-3">
            <label asp-for="@Model.subjectName" class="form-label custom-label">Subject Name</label>
            <input readonly asp-for="@Model.subjectName" value="@name" type="text" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="@Model.subjectName" class="form-label custom-label">For Day</label>
            <input readonly asp-for="@Model.Date" value="@date" type="text" class="form-control" />
        </div>

    <div asp-validation-summary="All" class="text-danger"></div>
    <button type="submit" Value="Add" class="btn btn-primary"> Add </button>
        <a asp-action="GetAllSubjects" asp-controller="Subject" class="btn btn-light">Cancle</a>
</form>
</body>

PllDoctor/Views/Attendance/CreateQRCode.cshtml
@model SubjectViewModel
@{
    ViewData["Title"] = "Generate QR Code";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generate QR-Code</title>
</head>
<body >
     <div class="container">
        <div class="row justify-content-center align-items-center" style="height: 80vh;">
            <div class="col-md-6 main-agileinfo">
                <div class="text-center" id="QRImage0">
                    <div class="wthree-text">
                            <label class="anim">
                            <img src="@ViewBag.QrCodeUri0" class="img-thumbnail"  />
                            </label>
                            <div class="clear"></div>
                     </div>
                </div>
                <div class="text-center" id="QRImage1">
                    <div class="wthree-text">
                        <label class="anim">
                            <img src="@ViewBag.QrCodeUri1" class="img-thumbnail" />
                        </label>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="text-center" id="QRImage2">
                    <div class="wthree-text">
                        <label class="anim">
                            <img src="@ViewBag.QrCodeUri2" class="img-thumbnail" />
                        </label>
                        <div class="clear"></div>
                    </div>
            </div>
        </div>
    </div> 
   
</body>
</html>
<script src="~/js/site.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

PllDoctor/Views/Attendance/GetAttendance.cshtml
@using PllDoctor.DTO
@model IEnumerable<AttendanceModelDTO>
@{
    ViewData["Title"] = "GetAttendance";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<header>
    <style>

    </style>
</header>
<body>
@if (Model.Count() > 0)
    {
        <div class="col-12">
            <center><h1><strong>Attendance OF This Day</strong></h1></center>
        </div>
    <div class="row-cols-md-auto">
    <div class="col-md-4">
        <a asp-action="AddStudent" asp-controller="Attendance" class="btn btn-success">Add Student Manually</a>
    </div>
    </div>
    <table class="table table-info table-hover mt-4">
        <thead class="table-dark">
        <th><center>Student Name</center></th>
        <th><center>Student Id</center></th>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td><center>@item.StudentName</center></td>
                    <td><center>@item.STDId</center></td> 
                </tr>
            }
        </tbody>
    </table>
   
}
else
{
    <div class="mt-5 alert alert-warning">
        <h1>NoT Founded Attendance For This Subject</h1>
    </div>
 }
</body>

PllDoctor/Views/Attendance/TheEnd.cshtml
@{
    ViewData["Title"] = "TheEnd";
    Layout = "~/Views/Shared/_TheEnd.cshtml";
}


    <div>
        <div class="w3-display-middle" id="QRImage3">
            <h1 class="w3-jumbo w3-animate-top w3-center"><code><strong>Thank You For Attention</strong></code></h1>
            <hr class="w3-border-white w3-animate-left" style="margin:auto;width:50%">
            <h3 class="w3-center w3-animate-zoom">🚫🚫🚫🚫</h3>
            <h6 class="w3-center w3-animate-zoom">The End</h6>
        </div>
    </div>